# Generated by Django 3.1.7 on 2021-04-08 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nakivo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='author',
        ),
    ]
